### ISSUE TITLE
User Editing

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/1872-Columbia-Map#10]
User will be able to add and edit information about sites.

**Comment by browncg2** [comment]
Android's .xml layouts (which we use Layoutinflator to display the pop-up) are pre-loaded during runtime; while there might be a workaround I have heard it is much slower.

http://developer.android.com/reference/android/view/LayoutInflater.html#inflate%28org.xmlpull.v1.XmlPullParser,%20android.view.ViewGroup%29

**Comment by josemvidal** [comment]
To be clear, I am referring to the user being able to enter/edit the text of a new/existing site.

You will probably have one layout for a site's detail info, but the text in it, and photo, will be different for each site.
