### ISSUE TITLE
Bonus feature: Gdrive save of new user-generated data

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/1872-Columbia-Map#14]
The easiest way to do this is to use java Serializable and write out the data as a binary blog.

However, it is probably better to use some standard text encoding (JSON or XML) and write the data out as a text file that can then be opened and edited in a text editor. 

The advantage there is that the admins can then edit this text file on their laptop. If they have hundreds of pages of text to enter they will much prefer this method. In fact, the text file itself could be generated by some other program.

**Comment by oa2013** [comment]
The Gdrive part of this feature isn't happening because of the issues with Google Play Services we brought up earlier. So far, we can attach a text file located in the data/data folder of the device and send it to anywhere using our email option.
