### ISSUE TITLE
Decide on Platform: windows or android or ios?

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/1872-Columbia-Map#2]

**Comment by browncg2** [comment]
On 10/1/2013, we visited the project location with Professor Marsh and now have a clear understanding of what she is asking for.  Professor Marsh wants a kiosk display with output to a flat-screen television which will be mounted on the wall.  The location currently does not have an internet connection so we do not know if we can use Google maps.  It appears Google maps does not work on PC, which is one of the reasons Android was considered.  Therefor, we have discussed using a computer-based operating system such as Windows or Linux to run an application, probably in Java.
