### ISSUE TITLE
Boxed primitive performance bug

### ISSUE THREAD

**Issue by huntleja** [SCCapstone/1872-Columbia-Map#22]
Within src/com/example/capstone/EditLocation.java

Such as on line 143: xLocation = new Double(xLoc).toString();

 Each time this is executed, a new instance, new object is created. However, object creation is not necessary and can be avoided. Creating object just for one method call is inefficient as the object can be garbage collected on the consecutive line.

A more efficient way to do this would be.

xLocation = Double.toString(xLoc);

This also occurs on line 144

**Comment by fagerburg** [comment]
Fixed, Thanks.
